// ===== NEMA Chemicals — Static Image Index =====
// Auto-generated list of all product images in images/ and images/products/
// Generated: 30/5/2026, 3:31:38 pm
// Optimized for mobile PWA — all images compressed to JPEG.

const IMAGE_INDEX = [
  "JONSONS BABY CREAM.jpg",
  "KESH KANTI.jpg",
  "NINE PANTS.jpg",
  "Unknown-1 copy 3.jpg",
  "Unknown-1 copy.jpg",
  "Unknown-1.jpg",
  "Unknown-12.jpg",
  "Unknown-13.jpg",
  "Unknown-2 copy 2.jpg",
  "Unknown-2 copy.jpg",
  "Unknown-2.jpg",
  "Unknown-3 copy.jpg",
  "Unknown-3.jpg",
  "Unknown-8.jpg",
  "Unknown-9.jpg",
  "Unknown.jpg",
  "colgate.jpg",
  "himalaya baby cream.jpg",
  "mamy poko.jpg",
  "maxfresh.jpg",
  "patanjali chywanprash.jpg",
  "patanjali ghee.jpg",
  "red paste .jpg",
  "sensodyne.jpg",
  "products/aashirvaad-atta.jpg",
  "products/amul-butter.jpg",
  "products/boroline.jpg",
  "products/boroplus-cream.jpg",
  "products/cadbury-5star.jpg",
  "products/cadbury-bournville.jpg",
  "products/cadbury-bournvita.jpg",
  "products/cadbury-celebrations.jpg",
  "products/cadbury-dairymilk.jpg",
  "products/cadbury-fruitnut.jpg",
  "products/cadbury-gems.jpg",
  "products/cadbury-oreo.jpg",
  "products/cadbury-perk.jpg",
  "products/cadbury-silk.jpg",
  "products/cadbury-silkoreo.jpg",
  "products/closeup-toothpaste.jpg",
  "products/coca-cola.jpg",
  "products/colgate-maxfresh.jpg",
  "products/colgate-toothpaste.jpg",
  "products/denver-deo.jpg",
  "products/dettol-soap.jpg",
  "products/deys-almond-oil.jpg",
  "products/deys-sarso-amla.jpg",
  "products/dove-shampoo.jpg",
  "products/everyday-ghee.jpg",
  "products/everyuth-aloe-facepack.jpg",
  "products/everyuth-aloevera-gel.jpg",
  "products/everyuth-body-lotion.jpg",
  "products/everyuth-face-pack.jpg",
  "products/everyuth-face-wash.jpg",
  "products/everyuth-peel-off-mask.jpg",
  "products/everyuth-scrub.jpg",
  "products/everyuth-tan-removal.jpg",
  "products/everyuth-walnut-scrub.jpg",
  "products/exit-agarwatti.jpg",
  "products/exo-dishwash.jpg",
  "products/exo-steel.jpg",
  "products/eye-tube.jpg",
  "products/ezee-liquid.jpg",
  "products/fair-and-handsome.jpg",
  "products/glow-lovely.jpg",
  "products/grocery-blurred.jpg",
  "products/haldiram-bhujia.jpg",
  "products/harpic-cleaner.jpg",
  "products/head-shoulders-shampoo.jpg",
  "products/images-1.jpg",
  "products/india-gate-rice.jpg",
  "products/jonson baby powder.jpg",
  "products/keo-karpin-oil.jpg",
  "products/lays-chips.jpg",
  "products/lizol-cleaner.jpg",
  "products/lux-soap.jpg",
  "products/maggi-noodles.jpg",
  "products/maggi-pazzta.jpg",
  "products/maggi-sauce.jpg",
  "products/mother-dairy-milk.jpg",
  "products/nc-logo-flask.jpg",
  "products/nema-3d-logo.jpg",
  "products/nema-chemicals-3d-logo.jpg",
  "products/nescafe-classic.jpg",
  "products/nescafe-gold.jpg",
  "products/nestle-cerelac.jpg",
  "products/nestle-everyday.jpg",
  "products/nestle-kitkat.jpg",
  "products/nestle-milk.jpg",
  "products/nestle-milkmaid.jpg",
  "products/nestle-munch.jpg",
  "products/nivea-cream.jpg",
  "products/parle-g.jpg",
  "products/patanjali alovera gel.jpg",
  "products/patanjali-aloevera.jpg",
  "products/patanjali-coconut.jpg",
  "products/patanjali-dant-kanti.jpg",
  "products/patanjali-dishbar.jpg",
  "products/patanjali-facewash.jpg",
  "products/patanjali-ghee.jpg",
  "products/patanjali-honey.jpg",
  "products/patanjali-noodles.jpg",
  "products/patanjali-oil.jpg",
  "products/patanjali-shampoo.jpg",
  "products/patanjali-toothpaste.jpg",
  "products/pepsodent-toothpaste.jpg",
  "products/red-bull.jpg",
  "products/surf-excel.jpg",
  "products/tata-dal.jpg",
  "products/tropicana-juice.jpg",
  "products/vim-dishwash.jpg",
  "products/whisper.jpg",
  "products/whitetone.jpg"
];
